### ISSUE TITLE
good work !

### ISSUE THREAD

**Issue by davephillips** [SVModular/SynthKit#1]
Linux Fedora 23
Rack 0.5.x

Just wanted to drop a note to let you know I've been building your modules without troubles on Fedora 23. Nice work so far ! :)

**Comment by JerrySievert** [comment]
awesome! thanks!

I've just released binaries for Mac, linux, and windows, which also include a much nicer UI and added a very simple 4 step sequencer based on the littlebits synth kit sequencer (which was the first sequencer I hooked up to my physical eurorack modules before I started building my own hardware).
