### ISSUE TITLE
Seq-8 outputs not following the pots settings.

### ISSUE THREAD

**Issue by veryfungi** [SVModular/SynthKit#11]
I tried the sequencer but the outputs are not behaving at all. Not even sure how to describe it. The Seq-4 works fine btw.

**Comment by JerrySievert** [comment]
yeah, I found and fixed the bug - not sure exactly when it got introduced.

next release will it, or if you compile from source.

**Comment by veryfungi** [comment]
I don't know how to compile so I will wait for the next release I guess. Thanks

**Comment by JerrySievert** [comment]
what platform are you on? windows, linux, or Mac?  I can do a quick binary release, if you want to install the plugin manually.

**Comment by JerrySievert** [comment]
new versions for each platform have been released, you should no longer see this issue.

**Comment by veryfungi** [comment]
Thank you Jerry for fixing the bug. I am using it now. One other thing I just noticed is the output does not follow the selector in real time. Only when stepping into the channel you're adjusting. To fill the sequencer with values I add a manual pules to the step input. I listen to the output, adjust the value and click 8 times to hear the change. If you know the notes in advance it's easy, but to do it on the fly it's not as easy as it could be. Thanks
