### ISSUE TITLE
Rotating Clock Divider can't be found

### ISSUE THREAD

**Issue by AnatolLocker** [SVModular/SynthKit#12]
Hi, since the last update to 0.6.1, integration of the "Rotating Clock Divider CV" seems to be broken in my patches: 
![bildschirmfoto 2018-07-23 um 17 54 34](https://user-images.githubusercontent.com/41620769/43129559-01d1d742-8f35-11e8-9c6c-7aeb627036bc.png)

**Comment by JerrySievert** [comment]
it's been renamed to better suit what it is - `shifting clock divider cv`
