### ISSUE TITLE
Missing tags?

### ISSUE THREAD

**Issue by darloth** [SVModular/SynthKit#13]
I've been trying to find some of these things using tags which it seems obvious they should have, and failing.

Here's a few that seemed obvious at least to me:

1x8 and 1x8 CV splitter are not under the Multiple tag.
None of the Clock- modules are under Clock Modulator tag.
None of the logical modules (And, Or, etc) are under the Logic tag.

**Comment by JerrySievert** [comment]
all tags should be correct in 1.0, going to go ahead and close this.
