### ISSUE TITLE
Feature Request: Reset on Seq-4 and Seq-8

### ISSUE THREAD

**Issue by rabramley** [SVModular/SynthKit#14]
Please could you add a reset trigger input for Seq-4 and Seq-8 to make it easier to sync them with other gear.

BTW, great plugins!

**Comment by JerrySievert** [comment]
I'll see what I can do right before the v1 port.

**Comment by JerrySievert** [comment]
added, just waiting for the plugin manager release.  I'll close this ticket when that occurs.

**Comment by JerrySievert** [comment]
and they're out, closing this ticket.
