### ISSUE TITLE
Cool recent release

### ISSUE THREAD

**Issue by blackearth2014** [SVModular/SynthKit#2]
Nice modules that you have developed. What is next in your development adventures?

**Comment by JerrySievert** [comment]
I've been working on some fx modules (which will be released in another repo), and for this I'm finishing up a rotating clock module, at which point I'll probably call this release "complete" beyond bug fixes and recompiles for new versions of rack.

any requests?

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by blackearth2014** [comment]
Jerry,

I like your release. If I have a request, it maybe beyond the scope of VCVRACK. So here goes. I would like to take your Or, And and other logic modules to combine Saw, Tri, Sine, Sqr and Noise waveform forms to generate a new waveform sound source. It’s cool that I can use what I am doing for modulation and driving FM inputs on VCO’s and LFO’s. But I would like a module that can convert the generated waveforms from the logic modules to perform as a VCO. 

When you hook up a scope to the output of your Or module after connecting two other waveform sources, you can see a whole new waveform. I want that waveform to output as a VCO waveforms. I am not looking for a wavetable module but something like Izotope’s Iris VST instruments. You can load a sound source or an analog waveform to create a patch. Take a look at https://www.izotope.com/en/products/create-and-design/iris.html. This can explain my thoughts better.

Major thanks,

This is your season
Omar Brown
Blessed House Media

On Jan 15, 2018, at 4:00 PM, Jerry Sievert <notifications@github.com> wrote:

I've been working on some fx modules (which will be released in another repo), and for this I'm finishing up a rotating clock module, at which point I'll probably call this release "complete" beyond bug fixes and recompiles for new versions of rack.

any requests?

**Comment by JerrySievert** [comment]
ah, so essentially a Korg DSS-1?

it would be fairly easy to piece one together with various modules (I've been planning on building one in hardware based on the sparkfun tsunami.

**Comment by blackearth2014** [comment]
I have never heard of this Korg DSS-1, but I am sure that I have heard it on many albums. If this is what you are shooting for, you got my support and respect. Cool Breeze!!!!

**Comment by JerrySievert** [comment]
it's Kong's "Digital Sampling Synthesizer" - full sized, very heavy keyboard with a floppy drive inside it for loading and saving samples and patches.  I have one (it's sitting in storage next to my Yamaha dx-7), and haven't used it in several years.

**Comment by blackearth2014** [comment]
You were going to make a module out of it or something?

**Comment by JerrySievert** [comment]
yeah, will give that a try.  I've released the rotating clock divider (but haven't updated the compiled releases yet), and have started my FXKit, then will work on a sample-based module or two, and am planning on writing one with an embedded javascript engine for people to develop against.

**Comment by JerrySievert** [comment]
following up - I've actually been working on this.

it'll likely be released via (CharredDesert)[https://github.com/JerrySievert/CharredDesert) - if I manage to get it done in the next couple of days, I'll update.

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by JerrySievert** [comment]
I've created a module named "Oscar" as part of Charred Desert - it will become available when rack 0.6.0 is released.

**Comment by blackearth2014** [comment]
Cool Breeze
