### ISSUE TITLE
Request for Rotating Clock Divider

### ISSUE THREAD

**Issue by rossco255** [SVModular/SynthKit#3]
The Rotating Clock Divider is a great module. Would it be possible to add the ability to change the behaviour of the rotation CV input so rather than cycling through the rotations one by one on a trigger, an input of 0v outputs the base state, 5v (or whatever max value) outputs the final state and the rest are all in between? It'd make it easier to use the rotation to generate drum fills with CV then return back to whatever rotation you're using as a base.

**Comment by JerrySievert** [comment]
it is - I'll add it to my list.

if you do development, the base work on all of this live in [SynthDevKit](https://github.com/JerrySievert/SynthDevKit), and is pretty easy to use as a base for clock modules.

I'm adding more though, I love clock modules.

**Comment by JerrySievert** [comment]
closing this, since you did it :)
