### ISSUE TITLE
No resets?

### ISSUE THREAD

**Issue by bubbleandsquawk** [SVModular/SynthKit#4]
It seems that among all of your clock related and clock dependent modules there is a lack of resets. I have to wonder if this is intentional or an oversight?

**Comment by JerrySievert** [comment]
oversight.  can add for the next release.

**Comment by bubbleandsquawk** [comment]
Nice! Thanks!

**Comment by JerrySievert** [comment]
I've been trying to figure out exactly where to put the reset ... I may end up switching jack components to something smaller (like in CharredDesert), in order to better fit it in.

when I wrote the underlying code to handle everything [SynthDevKit](https://github.com/JerrySievert/SynthDevKit), I included resets in everything, so it really is just a matter of hooking it up.

I'll see how much work it will be to convert over to the smaller jacks, and see how it looks, and let you know when reset is live.

**Comment by bubbleandsquawk** [comment]
The 4ms modules (RCD and SCD) seem to find sufficient lateral space for an extra socket, and 4hp seems to be enough space to squeeze two sockets side by side.

I'm sure you'll figure it out. :)

**Comment by JerrySievert** [comment]
<img width="118" alt="screen shot 2018-04-06 at 12 59 54 pm" src="https://user-images.githubusercontent.com/471270/38441682-7119c0a6-399a-11e8-9cb2-ce4a5babe501.png">

2 across, no problem - 3 across and labels not so fun :)

<img width="93" alt="screen shot 2018-04-06 at 1 00 45 pm" src="https://user-images.githubusercontent.com/471270/38441718-8f7a3d28-399a-11e8-9810-fb6dfcd3e2b1.png">

**Comment by jonheal** [comment]
Jerry,

I realize this is unsolicited, but I worked up a (re)design for the panel of your Rotating Clock Divider. It's obviously quite different from your existing designs and departs from the 4MS look, say I apoligize if this is an unwelcome intrusion, but if you like it, I would be willing to do similar designs for your other modules.

![sk-spec-design](https://user-images.githubusercontent.com/33180867/39708450-3e9b2418-51e5-11e8-8c36-33b5e7313263.png)

**Comment by jonheal** [comment]
I don't if you noticed it or not, Jerry, but yesterday, I took the liberty of working up a design for your Rotating Clock Divider. Then I realized I kind of had my paradigm backwards for how IN vs. OUT jacks are typically identified so I deleted my post. Since this was unsolicited to begin with, I wondered if I should just stay quiet. But I couldn't resist, and I reworked the design(s). They  obviously depart from the 4MS look, but if you like these, I would be willing to work up designs for the remaining members of the "SynthKit" line of modules. If not, ignore. :-)

![dk-dividers](https://user-images.githubusercontent.com/33180867/39816938-bf1b6d42-536a-11e8-89b8-fab797030d90.png)

**Comment by bubbleandsquawk** [comment]
I'm a big fan of that design Jon. Nice work.

**Comment by jonheal** [comment]
One more ...

![sk-logic-and](https://user-images.githubusercontent.com/33180867/39827717-cc6924dc-5386-11e8-9922-f762d664ad14.png)

**Comment by JerrySievert** [comment]
thanks @jonheal ! they look great!

any chance I can get you to try them using the components that SynthKit uses?  see https://github.com/JerrySievert/rack-components for the selection.

colors are easy to change on them, but I prefer the look and feel.

**Comment by jonheal** [comment]
Here is the AND module from above using your small gray jacks:

![sk-logic-and-sk-components](https://user-images.githubusercontent.com/33180867/39828514-4f699dc4-5389-11e8-9de1-6ddb39b47ee2.png)

For the Divider CV, I must say I am partial to my own knurled small knob. :-) Ruminate on it for a while. Maybe it will grow on you.

**Comment by jonheal** [comment]
A big version:

![sk-logic-and-sk-components-big](https://user-images.githubusercontent.com/33180867/39829145-736186a4-538b-11e8-82b5-52832fc63ee3.png)

**Comment by jonheal** [comment]
The Divider CV (100% and magnified) with resized bits for your jacks, but still including my knurled knobs:

![sk-rotating-clock-divider-cv-sk-components](https://user-images.githubusercontent.com/33180867/39837249-ef169740-53a3-11e8-9189-05c40c7a9878.png)

**Comment by JerrySievert** [comment]
![3out](https://user-images.githubusercontent.com/471270/39883884-f355f032-543c-11e8-8797-2e5a404c8738.png)

you can see the knob difference here.  (well, a hack job of it)

**Comment by JerrySievert** [comment]
![non](https://user-images.githubusercontent.com/471270/39884051-73a08c2a-543d-11e8-8439-f9e20be562ee.png)

less of a hack job.

**Comment by jonheal** [comment]
Would you be open to toning down the black on the knobs a little? As the only jet black objects on the panel, I think it is too jarring.

-- 
Jon Heal 
http://www.theheals.org/ 
Have a nice day!
 



----------------------------------------

**Comment by JerrySievert** [comment]
yes, absolutely.  agree with the jarring jet black.  happy to tone it down to whatever, it's easy to add another set of knobs to the repo that's included.

**Comment by jonheal** [comment]
I can work on it when I get home from work.
-- 
Jon Heal 
http://www.theheals.org/ 
Have a nice day!
 



----------------------------------------

**Comment by JerrySievert** [comment]
awesome.  it's easy for me to just do a copy and set the colors, as long as the colors are defined.  I mean, those svg's were originally programmatically generated, then loaded into Inkscape to get rack to figure them out.  I know my way around them by now :)

**Comment by jonheal** [comment]
And you are willing to shrink your buttons as you have done in the mockup example?

**Comment by JerrySievert** [comment]
yeah, if the "small" versions don't fit, I'm happy to shrink them until they do - as I said, built programmatically, so not too big of a deal.

**Comment by JerrySievert** [comment]
also can change the jack outer ring to match the same black as the knobs.

**Comment by jonheal** [comment]
Two other things:
1. What is the largest value the knobs would reach? Right now, there is not room for three digits. if you wanted to go to 128 like the Doepfer device, I would need to do some more squishing.
2. I used commercial fonts, which is not a big deal for most of the text on the panels because I would just turn it into outlines, but I would assume those changing number values would need to remain as a font, so I need to find an equivalent font that can be redistributed for those numbers.

**Comment by JerrySievert** [comment]
sequencers: 0-8 and 0-11.

(octave for 0-8, and note for 0-11)

**Comment by jonheal** [comment]
I switched to a Google font: Teko. Can you live with two different jacks? The jacks on a dark background need a light ring, I think.

![sk-rotating-clock-divider-cv-sk-components](https://user-images.githubusercontent.com/33180867/39898476-e18a4c2a-5484-11e8-862a-c0d8621319e1.png)

My one comment is that I think it would improve the look of your knobs at 100% (on a non-retina monitor) if the inner circle was shrunk just a bit to expose a bit more of the yellow ring. The yellow kind of gets lost in pixelization at 100%. I will make an example when I get home today.

**Comment by jonheal** [comment]
A subtle difference, but meaningful, I think:

![sk-rotating-clock-divider-cv-sk-components](https://user-images.githubusercontent.com/33180867/39937545-1c4b181e-551e-11e8-8f27-e89b768badb0.png)

**Comment by JerrySievert** [comment]
shrunk the inner circle locally - can you send an SVG of one of the designs, so I can throw something together programmatically to see a final result?

**Comment by jonheal** [comment]
Now ... hopefully this won't  cause problems, but I use Affinity Designer, not Inkscape. There are lots of SVG export options in Designer, the majority of which I was unsure about. In any case, I exported a version with everything intact (screws, jacks, knobs) and one with all of that stuff removed. I also saved the screw as a separate file. I can also send you the positions of everything if that is helpful. But it may not be ...

[SK.zip](https://github.com/JerrySievert/SynthKit/files/1996653/SK.zip)

Hopefully, this works ...

Thank you for letting me help with this.

**Comment by JerrySievert** [comment]
awesome, and no, thank you for your awesome designs!

I'll take a look, and let you know what works and what doesn't.  I had started using adobe tools, and found that they didn't work correctly in rack, then switched to Inkscape, which I hate to use (I have a Mac), and then finally to writing code to build svg's, which still didn't work in rack, but after a step through Inkscape would work.

I'll figure out the process and share.

**Comment by JerrySievert** [comment]
awesome, and no, thank you for your awesome designs!

I'll take a look, and let you know what works and what doesn't.  I had started using adobe tools, and found that they didn't work correctly in rack, then switched to Inkscape, which I hate to use (I have a Mac), and then finally to writing code to build svg's, which still didn't work in rack, but after a step through Inkscape would work.

I'll figure out the process and share.

**Comment by jonheal** [comment]
By the way, when I opened your knob in Designer, the inner circle was duplicated. Two of  'em on top of each other. In my files, I deleted one of them.

**Comment by JerrySievert** [comment]
yup, you can thank Inkscape for that - and that was after cleaning up the mess that Inkscape made of the source svg (which was just a polygon, rect, and circle)

**Comment by JerrySievert** [comment]
example of the code that built them:

```
var draw = SVG(document.documentElement).size('10mm', '10mm').fill('#000');
var outer_knob = draw.polygon(polygon.to_svg_string(polygon.calculate(20, 20, 12, 10)));
outer_knob.move(0, 0).fill('#000');
var red_knob = draw.polygon(polygon.to_svg_string(polygon.calculate(15, 15, 12, 7.5)));
red_knob.move(2.5, 2.5).fill('#f30000');
var inner_knob = draw.circle(13).move(3.25, 3.25).fill('#c00000');
var edge = draw.rect(2, 7).fill('#000000').move(8.75, 1);
```

`polygon` is a helper method that generates a polygon - not much to mess up even :/

**Comment by JerrySievert** [comment]
<img width="180" alt="screen shot 2018-05-11 at 12 55 03 pm" src="https://user-images.githubusercontent.com/471270/39944189-8f0d0820-551a-11e8-9d10-707d16a43fe7.png">

heh, here it is with only changing out the SVG - I'll run it through Inkscape and see if there's any change.

**Comment by JerrySievert** [comment]
hm. nothing I'm doing is getting it to work in rack - you can see for yourself by opening the plugins directory for rack, and replacing `SynthKit/res/RotatingClockDivider.svg` - any ideas?

**Comment by jonheal** [comment]
I will play with it in a bit.

**Comment by JerrySievert** [comment]
as an aside, looking at the source and it looks just fine.

**Comment by JerrySievert** [comment]
the good news is that once this is figured out, it should be pretty easy to get it all replaced.

**Comment by jonheal** [comment]
I have to take my son out for a while. When I get back, I will fool around with it.

**Comment by JerrySievert** [comment]
sounds good! wondering if switching to email would make more sense.

**Comment by jonheal** [comment]
Write me here >> jon@theheals.org

I had some success. Turned out to be a pretty easy fix.

![image](https://user-images.githubusercontent.com/33180867/39952589-edfe7470-5567-11e8-8b96-d29bba5416fe.png)

**Comment by bubbleandsquawk** [comment]
Curious as to how this is coming along?

**Comment by jonheal** [comment]
I’ll see if I can get something to you by the weekend, Jerry.

--
Jon Heal
http://www.theheals.org/
Have a nice day!

**Comment by JerrySievert** [comment]
code's all there, assets for all but one thing - you can compile yourself, or I can do a release.  was waiting on the one (new) thing before getting it into rack's plugins.

**Comment by JerrySievert** [comment]
these are all live, closing.
