### ISSUE TITLE
Feature request: labels on the prime and fibonacci clock dividers

### ISSUE THREAD

**Issue by h00g** [SVModular/SynthKit#8]
I suggest that the labels are added so that one can see on which beat each output fire.
![image](https://user-images.githubusercontent.com/37247576/37245214-23df61de-2495-11e8-8fbb-56ddd3be4bec.png)

**Comment by rossco255** [comment]
I'm a github/dev noob but here's an SVG for each that works. I've made the numerals as large as I think they can be, let me know if it's readable or not.
[labelledPanels.zip](https://github.com/JerrySievert/SynthKit/files/1800857/labelledPanels.zip)
Just replace the files in /Plugins/SynthKit/res

**Comment by h00g** [comment]
I could probably help you update the repository but I do not have access to create a branch.

GitHub in particular is a bit new to me but doftware configuration management is a field I generally fell confident in.

**Comment by h00g** [comment]
This is the issue I encounter.
![image](https://user-images.githubusercontent.com/37247576/37272361-ad428216-25d6-11e8-85b2-3c8b25acdd5e.png)

**Comment by h00g** [comment]
You could try adding me as collaborator if the current setting is "Restrict editing to collabors only".
![image](https://user-images.githubusercontent.com/37247576/37272490-053081b2-25d7-11e8-87b1-fff0babd35b6.png)
![image](https://user-images.githubusercontent.com/37247576/37272503-10c7b090-25d7-11e8-8e77-2bde1756af8d.png)
![image](https://user-images.githubusercontent.com/37247576/37272510-1c4cf894-25d7-11e8-80aa-9efaff29f09f.png)

**Comment by JerrySievert** [comment]
sorry @h00g, I'm not giving write access unless someone has already contributed and made substantial additions.  you're welcome to create a Pull Request, which will allow for discussion, and decisions to be made though!  that's the typical way to contribute with GitHub.

please note, though, if the font doesn't match, I'm likely not going to accept the PR.

as an aside, what @rossco255 was suggesting is to save the `svg` to your local `plugins` directory, and override your local copy, not to make an update to the repository itself.

**Comment by rossco255** [comment]
Font used is Audiowide Regular, so should be same as the rest of the modules

**Comment by h00g** [comment]
Thanks for the info and maybe it's better that @rossco255 makes the pull request since I just made the suggestion to add digits and presented the Photoshop mock up.

It would be interesting to hear if you liked the suggestion conceptually @JerrySievert

**Comment by JerrySievert** [comment]
conceptually, I'm just fine with it - I had been developing modules so quickly that I put together a quick template and kept reusing it.  as long as it matches, and looks good, I'm likely to accept the PR.

if I don't like it, I'll probably ask for some sort of change, but that's part of what the commenting part of a PR is all about.

just note, I've updated the modules to 0.6.0 to get ready for the release, so any changes won't take affect until the new rack release.

**Comment by rossco255** [comment]
I've created a pull request for this, as well as including the different rotating clock behaviour I suggested [here](https://github.com/JerrySievert/SynthKit/issues/3) last month. This is my first time programming anything and using git, feel free to let me know of any errors or bad etiquette!

**Comment by JerrySievert** [comment]
closing as this is merged.
